### PR TITLE
Ported 'content element' feature from EXT:news

### PR DESCRIPTION
**Pull request by kitzberger**

### CODE REVIEW

**Comment by derhansen** [comment]
Thanks for your PR. I will need to review it carefully (which will take some time) and have some doubt about if all code is really required (e.g. the `Content` class with all the properties or the mapping of the properties in `Configuration/Extbase/Persistence/Classes.php`). 

Also the new changes do not include any tests, so this is something that needs to be added. 

ext:news provides the possibility to enable/disable the feature and since the Event TCA already is really huge with numerous of tabs, it must also be possible to enable/disable the feature in extension settings.

**Comment by kitzberger** [comment]
@derhansen, sure thing: will migrate feature toggle as well!

**Comment by kitzberger** [comment]
@derhansen, introduced a feature flag and simplified the content model. Should be easier to review now ;-)

**Comment by derhansen** [comment]
I'm really sorry for not responding on this PR in time. I'm also sorry that I will not merge the PR, since after carefully thinking about this feature, I think it will be best to provide it as a separate TYPO3 extension which extends the main extension. Reason for this is, that if the main extension gets too "big" in regards of code/features, it will be much more work for me to maintain it.

**Comment by derhansen** [comment]
Closing issue, since the feature has been releases as standalone extension - https://extensions.typo3.org/extension/sf_event_mgt_contentelements

**Pull request closed without merging**
