### PR TITLE
Add Category Filter to Search Demand object

### PR DESCRIPTION
**Pull request by WebsiteDeveloper**
Hello,

For a project we needed to be able to Filter the Search List by Categories selected in an html select element.
This code is just a first try at solving this problem cause i couldn't find any good documentation in case this feature is already available.
I just wanted to spark some discussion.
I'm still quite new to typo3 extension development so if there is a better way to solve the same issues i would be happy to hear it :)
And if thats the case maybe it should be added to the extension documentation for someone new to typo3 development in general, like me.

### CODE REVIEW

**Comment by derhansen** [comment]
Hi,

what you would like to archive can be done using the existing search action together with the `$overwriteDemand` variable.

First you need to make sure, that you have unchecked the "Disable override demand" setting in the plugin (override/overwrite spelling will be corrected within the next release)

Second you need to add an input field (plain HTML field - just for demonstration purposes) to your search template in the `<f:form ...` section like shown below

```
<input type="text" name="tx_sfeventmgt_pievent[overrideDemand][category]">
```

Now you can enter the uid od a category in the new input field and search for events matching the category uid (and searchterm).

This is just an example, of course you should use a select field for the categories. The `searchAction` passes all selected categories from the plugin to the view, so you can easily create a select field with all category names.

Just ping me, if you need additional help

**Comment by WebsiteDeveloper** [comment]
@derhansen Thanks for the help.
I'll try that out 
Maybe you could add such an example to the docs? Might really help people like me just getting into extension development.

**Comment by WebsiteDeveloper** [comment]
@derhansen The option you suggested does not quite lead to the right result

The issue is:
1. I have a Typo3 page where the plugin is selected and categories are selected (kind of a prefiltered event list) for example only those with category 17
2. When i then use the override demand object the filter in the plugin gets overridden whereas i want to show the events that have the category 17 AND the category selected in the filter

**Comment by derhansen** [comment]
I have planned to implement a category conjuction (combine categories with AND/OR/NOTOR/NOTAND) in the next version of the extension. 

See: https://github.com/derhansen/sf_event_mgt/issues/477

**Comment by WebsiteDeveloper** [comment]
@derhansen If you could elaborate a bit how you would implement this i might be able to provide another pull request :)

**Pull request closed without merging**
