### PR TITLE
Use f:link.action viewhelper instead of link.page

### PR DESCRIPTION
**Pull request by spfeifer**
This fixes an issue with link generation if route enhancers are configured

### CODE REVIEW

**Comment by derhansen** [comment]
@spfeifer Thanks a lot for your PR. Could you provide information about, how to reproduce the issue the PR fixes?

**Comment by spfeifer** [comment]
In my site configuration I created a routeEnhancer for the extension like this:
`
routeEnhancers:
  EventPlugin:
    type: Extbase
    extension: SfEventMgt
    plugin: Pievent
    routes:
      - { routePath: '/', _controller: 'Event::list' }
      - { routePath: '/{event_title}', _controller: 'Event::detail', _arguments: {'event_title': 'event'} }
      - { routePath: '/{event_title}/ical', _controller: 'Event::icalDownload', _arguments: {'event_title': 'event'} }
      - { routePath: '/{event_title}', _controller: 'Event::registration', _arguments: {'event_title': 'event'} }
      - { routePath: '/save-registration/{event_title}', _controller: 'Event::saveRegistration', _arguments: {'event_title': 'event'} }
      - { routePath: '/save-registration-result/{eventuid}/{save_registration_result}/{hmac}', _controller: 'Event::saveRegistrationResult', _arguments: {'eventuid': 'eventuid', 'result': 'result', 'hmac': 'hmac'} }
      - { routePath: '/confirm-registration/{reguid}/{hmac}', _controller: 'Event::confirmRegistration', _arguments: {'reguid': 'reguid', 'hmac': 'hmac'} }
      - { routePath: '/cancel-registration/{reguid}/{hmac}', _controller: 'Event::cancelRegistration', _arguments: {'reguid': 'reguid', 'hmac': 'hmac'} }
      - { routePath: '/location/{location_title}', _controller: 'Event::list', _arguments: {'location_title': 'overwriteDemand/location'}}
      - { routePath: '/speaker/{speaker_name}', _controller: 'Event::list', _arguments: {'speaker_name': 'overwriteDemand/speaker'}}
      - { routePath: '/organisator/{speaker_name}', _controller: 'Event::list', _arguments: {'organisator_name': 'overwriteDemand/organisator'}}
      - { routePath: '/category/{category_title}', _controller: 'Event::list', _arguments: {'category_title': 'overwriteDemand/category'}}
      - { routePath: '/{year}/{month}', _controller: 'Event::calendar', _arguments: {'year': 'overwriteDemand/year', 'month': 'overwriteDemand/month'}}
    defaultController: 'Event::list'
    requirements:
      eventuid: '[0-9]{1..3}'
      reguid: '[0-9]{1..3}'
      result: '[0-8]'
      hmac: '^[a-zA-Z0-9]{40}$'
    aspects:
      event_title:
        type: PersistedAliasMapper
        tableName: 'tx_sfeventmgt_domain_model_event'
        routeFieldName: 'slug'
      location_title:
        type: PersistedAliasMapper
        tableName: 'tx_sfeventmgt_domain_model_location'
        routeFieldName: 'slug'
      speaker_name:
        type: PersistedAliasMapper
        tableName: 'tx_sfeventmgt_domain_model_speaker'
        routeFieldName: 'slug'
      organisator_name:
        type: PersistedAliasMapper
        tableName: 'tx_sfeventmgt_domain_model_organisator'
        routeFieldName: 'slug'
      category_title:
        type: PersistedAliasMapper
        tableName: 'sys_category'
        routeFieldName: 'slug'
`

After this I created a plugin with the calendar view and the links that were generated weren't the way the config said. The URLs (e.g.: /events/2019/12) were working, but the links weren't generated that way.

**Comment by spfeifer** [comment]
Done :)

**Comment by derhansen** [comment]
Merged into development

**Pull request closed without merging**
