### PR TITLE
Show the registration link in detail view when registration is enabled.

### PR DESCRIPTION
**Pull request by Konafets**
The current condition based on a non-existent property.

### CODE REVIEW

**Comment by tmotyl** [comment]
registrationPossible is a method -> getRegistrationPossible . Can you validate that this method is not called?

**Comment by Konafets** [comment]
@tmotyl You are right. The `Registration` link wasn't shown but it is when I add the parenthesis.

**Comment by derhansen** [comment]
@Konafets Please check the FAQ section for all cases, where `event.registrationPossible` will return `true` - https://docs.typo3.org/typo3cms/extensions/sf_event_mgt/Faq/Index.html#when-does-event-registrationpossible-return-true

When you add parenthesis to `event.registrationPossible`, Fluid can't resolve the method and will output a string.

Working example:

```
<f:debug>{event.registrationPossible}</f:debug>
```

This will either return `true` or `false`

Non working example with parenthesis:

```
<f:debug>{event.registrationPossible()}</f:debug>
```

This will always return the string `'{event.registrationPossible()}'`. When using this in your if-condition, fluid will always render the `then` child, since the condition contains a string.

**Comment by derhansen** [comment]
@Konafets I can help you with this tomorrow, when we meet in person :-)

**Pull request closed without merging**
