### PR TITLE
[FEATURE] Add support for bw_captcha

### PR DESCRIPTION
**Pull request by maikschneider**
This PR adds a new captcha type `bwCaptcha`. 

* It is required to have the [bw_captcha](https://github.com/maikschneider/bw_captcha) extension installed. Not sure if this should be checked?
* Minor refactoring of `RegistrationValidator::getValidator()`

Documentation will be added in case this feature is accepted.

### CODE REVIEW

**Comment by derhansen** [comment]
I will not add direct support for the extension in terms of requiring external classes (not even optional) or adding dedicated partials. 

I however see a simple possibility for you to integrate the feature into your extension. If I add a new PSR-14 event in `RegistrationValidator` (see #1208), then your extension can add an EventListener for that event and perform required validations. PSR-14 Event would include `$this->result`, `$this->settings`, `$type` and `$field`. 

You extension could additionally include the required TypoScript setting (as it already does for ext:form related settings), which then can be consumed from the new PSR-14 event in #1208. 

In order to provide a template for the bw_catcha field, you could add a template override in your TypoScript (e.g. `plugin.tx_sfeventmgt.view.partialRootPaths.999999 = EXT:bw_catcha/Resources/Private/Frontend/Partials/SfEventMgt/`), which users of sf_event_mgt then can include in their custom templates. 

This all would make it possible to integrate the functionality into your extension, so it would ship support for ext:form and ext:sf_event_mgt. What do you think? If ok, I will add the PSR-14 event suggested in #1208 for v7.x and the TYPO3 v13 branch of the extension.

**Comment by maikschneider** [comment]
Oh, great idea. This is way better, thank you!

**Comment by derhansen** [comment]
@maikschneider Here we go: https://github.com/derhansen/sf_event_mgt/commit/9d7846b3371d17fe35d5fccbe7dd6718adafe6a6

Example usage:

```
    public function __invoke(ModifyRegistrationValidatorResultEvent $event): void
    {
        $event->getResult()->forProperty('zip')->addError(new Error('Error for ZIP field', 1726287471));
    }
```

Just ping me if you have any problems or questions

**Comment by maikschneider** [comment]
Thanks, works like a charm!

**Pull request closed without merging**
